version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/appflask"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/appflask"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/Terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
