apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app-container
    image: hengabay7/flask-app:latest
    ports:
    - containerPort: 5000