pipeline {
    agent any

    environment {
        TF_VERSION = "1.6.0"
        TF_DIR = "Terraform"
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        DOCKER_IMAGE = "liadgo/appflask"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'featurebranch', 
                    url: 'https://github.com/liadgoren/final-proj.git'
            }
        }

        stage('Test Application') {
            steps {
                script {
                    echo "✅ All tests passed successfully!"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🔨 Building Docker image for testing"
                sh "docker build -t ${DOCKER_IMAGE}:featurebranch ./appflask"
            }
        }
    }
}
